config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users

  get  '/help',    to: 'start_pages#help'
  get  '/about',   to: 'start_pages#about'
  get  '/contact', to: 'start_pages#contact'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :relationships,       only: [:create, :destroy]
  resources :tasks,    only: [:create, :destroy]
  
  root 'start_pages#home'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resource :user do
    get :search, on: :collection
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_many :tasks, dependent: :destroy
  
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # 試作feedの定義
  # 完全な実装は次章の「ユーザーをフォローする」を参照
  def feed
    #Task.where("user_id = ?", id)
    Task.where("user_id IN (?) OR user_id = ?", following_ids, id)
  end
  
   #ユーザーをフォローする
  def follow(other_user)
    followings << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    relationships.find_by(follow_id: other_user.id).destroy
  end
  
  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    followings.include?(other_user)
  end
  
  def self.search(search)
    return User.none unless search
    Post.where(['content LIKE ?', "%#{search}%"])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :logged_in_user, only: [:edit, :update, :destroy,
                                        :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  
  def new
    @user = User.new
  end
  
  def search
    if params[:name].present?
      @users = User.where('name LIKE ?', "%#{params[:name]}%")
    else
      @users = User.none
    end
  end
  
  def show
    @user = User.find(params[:id])
    #@tasks  = Task.order('limit_date').all
    @tasks = @user.tasks.paginate(page: params[:page],per_page: 20)
    @status = ['予定', '実施中', '実施済']
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ようこそ"
      redirect_to @user #redirect_to user_url(@user.id)　オブジェクトを一意に表す値(id)を取得しようとする
    else                    
      render "new"
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "編集に成功しました"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.followings.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  
  
  
  private
   
      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end
      
      # beforeアクション

    
    
    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
   #引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :follow_id, @user.id %></div>
  <%= f.submit "フォロー", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<form method="POST" action="/tasks">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div>
    <label for="content">Task Name</label>
    <input id="content" name="content" type="text" required>
  </div>
  <div>
    <select name="state">
      <% @status.each_with_index do |s,i| %>
      <option value="<%= s %>"><%= s %></option>
      <% end %>
    </select>
    <label>Task State</label>
  </div>
  <div>
    <input type="date" name="limit_date" required>
    <label>Task Limit Day</label>
  </div>
  <p>
    <button type="submit">create</button>
  </p>
</div>
</form>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(follow_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "ユーザー編集") %>
<h1>編集ページ</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード（もう１度ご入力ください）" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "変更を保存", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a rel="noopener"  href="http://gravatar.com/emails" target="_blank">変更</a>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, '新規登録') %>
<h1>新規登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
    
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード（もう１度ご入力ください）" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "アカウント作成", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/search.html.erb
<h1>ユーザー検索</h1>
<%= form_with url: search_user_path, method: :get, local: true do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "検索" %>
<% end %>
<table>
  <thead>
    <tr>
      <th>検索結果(名前)</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= gravatar_for(user, size: 30) %></td>
        <td><%= link_to user.name, user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <!--%= render "form" %-->
    <% if @user.following?(current_user) && current_user.following?(@user) %>
      <%= render 'shared/show_tasks' %>
      <%= will_paginate @tasks %>
    <% else @user == current_user %>
      <%= render 'shared/show_tasks' %>
      <%= will_paginate @tasks %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "プロフィール", @user %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
     <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
     <% end %>
  </div>
</div>