config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users

  get  '/help',    to: 'start_pages#help'
  get  '/about',   to: 'start_pages#about'
  get  '/contact', to: 'start_pages#contact'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :relationships,       only: [:create, :destroy]
  resources :tasks,    only: [:create, :destroy]
  
  root 'start_pages#home'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resource :user do
    get :search, on: :collection
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="tasks">
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>状態</th>
          <th>タスク名</th>
          <th>期限</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render @feed_items %>
      </tbody>
    </table>
　</div>  
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_show_tasks.html.erb
<h3>Todoリスト(自分のみ)</h3>
  <ol class="tasks">
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>状態</th>
          <th>タスク名</th>
          <th>期限</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
       <%= render @tasks %>
      </tbody>
    </table>
  </div>  
  </ol>
<%= will_paginate @tasks %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">　
    <strong id="followings" class="stat">
      <%= @user.followings.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/shared/_task_form.html.erb
<%= form_for(@task) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.select :state,  [["予定","予定"],["実施中","実施中"],["実施済","実施済"]],
    { include_blank: false,  selected: "予定" },{class: 'form-control'} %>
    
    <%= f.text_area :content, placeholder: "タスク内容を記入して下さい", class: 'form-control' %>
    
    <%= f.datetime_select :limit_date, {use_month_numbers: true}, class: 'form-control' %>

   
  </div>
  <%= f.submit "作成", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "プロフィール", current_user %></span>
<!--<span> %= pluralize(current_user.microposts.count, "micropost") % </span> -->