config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users

  get  '/help',    to: 'start_pages#help'
  get  '/about',   to: 'start_pages#about'
  get  '/contact', to: 'start_pages#contact'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :relationships,       only: [:create, :destroy]
  resources :tasks,    only: [:create, :destroy]
  
  root 'start_pages#home'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resource :user do
    get :search, on: :collection
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "概要",   about_path %></li>
      <li>
       <a href="https://twitter.com/sinpujinrou" target="_blank" rel="noopener">お問い合わせはこちら</a>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-inverse navbar-fixed-top ">
  <div class="container">
    <%= link_to "Todo app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li class="header-right"><%= link_to "ホーム",   root_path %></li>
        <li class="header-right"><%= link_to "ヘルプ",   help_path %></li>
        <% if logged_in? %>
          <li class="header-right"><%= link_to "ユーザー検索", search_user_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "ユーザーページ", current_user %></li> <!--user_path(current_user)-->
              <li><%= link_to "編集", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="header-right"><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    　<%= yield %>
    　<%= render "layouts/footer" %>
    　<%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>